### ISSUE TITLE
How can I specify the alternative hypothesis for Tamhane's T2 Test?

### ISSUE THREAD

**Issue by fiuzatayna** [cran/PMCMRplus#2]
It currently only uses `two.sided`. Is it supposed to only work like that?

Thanks!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by fiuzatayna** [comment]
Thanks for the quick reply @gaborcsardi ! I'll get in contact :)
